-- Track whether a trade was system-generated or adopted from broker holdings.
ALTER TABLE trades ADD COLUMN origin TEXT DEFAULT 'system';
-- Values: 'system' (generated by ML/approval flow), 'adopted' (imported from broker)

-- Update existing adopted trades
UPDATE trades SET origin = 'adopted' WHERE order_id LIKE 'ADOPTED-%';
