"""Algo + user watchlist, sectors, universe symbols.

Moved verbatim out of app.py's create_app; endpoints close over
(app, ctx, deps) supplied by register().
"""

import logging
from typing import TYPE_CHECKING, Any

from fastapi import (
    Depends,
    FastAPI,
    HTTPException,
)

if TYPE_CHECKING:
    from yolovest.context import AppContext
    from yolovest.dashboard.deps import Deps

logger = logging.getLogger(__name__)


def register(app: "FastAPI", ctx: "AppContext", deps: "Deps") -> None:
    verify_credentials = deps.verify_credentials

    # ------------------------------------------------------------------
    # Watchlist & Market Data
    # ------------------------------------------------------------------

    @app.get("/api/watchlist")
    async def get_watchlist(user: str = Depends(verify_credentials)) -> list[dict[str, Any]]:
        """Algorithmic watchlist (auto-generated by market-scan)."""
        return await ctx.db.get_watchlist()

    @app.get("/api/user-watchlist")
    async def get_user_watchlist(user: str = Depends(verify_credentials)) -> list[dict[str, Any]]:
        """User-managed watchlist with scores from algorithmic scan."""
        return await ctx.db.get_user_watchlist()

    @app.post("/api/user-watchlist")
    async def add_user_watchlist_symbol(
        body: dict[str, Any],
        user: str = Depends(verify_credentials),
    ) -> dict[str, Any]:
        """Add a symbol to the user watchlist."""
        symbol = body.get("symbol", "").strip().upper()
        if not symbol:
            raise HTTPException(status_code=400, detail="symbol is required")
        sector = body.get("sector")
        notes = body.get("notes")
        ok = await ctx.db.add_user_watchlist_symbol(symbol, sector, notes)
        return {"success": ok, "symbol": symbol}

    @app.delete("/api/user-watchlist/{symbol}")
    async def remove_user_watchlist_symbol(
        symbol: str,
        user: str = Depends(verify_credentials),
    ) -> dict[str, Any]:
        """Remove a symbol from the user watchlist."""
        ok = await ctx.db.remove_user_watchlist_symbol(symbol)
        if not ok:
            raise HTTPException(status_code=404, detail=f"Symbol {symbol} not found in user watchlist")
        return {"success": True, "symbol": symbol.upper()}

    @app.get("/api/sectors")
    async def get_sector_rotation(user: str = Depends(verify_credentials)) -> dict[str, Any]:
        """Sector rotation analysis."""
        return await ctx.db.get_sector_rotation()

    @app.get("/api/universe-symbols")
    async def get_universe_symbols_list(
        _user: str = Depends(verify_credentials),
    ) -> list[str]:
        """All symbols in the OHLCV universe (for search/autocomplete)."""
        from yolovest.data.nse_symbols import get_universe_symbols as get_syms
        universe = ctx.config.scanning.universe
        return get_syms(universe)

